### ISSUE TITLE
Code is missing :)

### ISSUE THREAD

**Issue by SEJeff** [30x/dispatcher#1]
I'm guessing you're waiting to OSS this for some reason?

**Comment by whitlockjc** [comment]
Nah, it's open source from the start.  I was working on the design document _(`README.md`)_ but got sidetracked with project management stuff.  I'll get the `README.md` committed soon and start working on this immediately after.

**Comment by SEJeff** [comment]
Sorry I'm confused. You forgot to publish the source and will soon, or you have published it elsewhere. I've not seen it yet :)

**Comment by whitlockjc** [comment]
This code hasn't even been written yet.  ;)  It's a new project, built from the ground up in the open.
