### ISSUE TITLE
Nginx status endpoint

### ISSUE THREAD

**Issue by AdamMagaluk** [30x/dispatcher#13]
In many cases have a load balancer that sits in front of all nodes in a cluster and routes http traffic to each of dispatcher. Most cloud providers allow an optional health check and some require it. 

Should we allow for status endpoint on nginx? /status with any host defaults to 200?

**Comment by whitlockjc** [comment]
Well, what's the point of the status...to check that our router is up or to check that the deployed applications are up?

**Comment by AdamMagaluk** [comment]
Check if the router is up.

**Comment by whitlockjc** [comment]
That's what I figured, just wanted to be sure.  Let's talk offline.
