### ISSUE TITLE
support weights

### ISSUE THREAD

**Issue by mpnally** [30x/dispatcher#21]
One of our primary use-cases is the implementation of so-called "blue-green" upgrades. In a "blue-green" upgrade, you have a set of existing instances of a particular revision of a component, and you bring up an additional set of instances for the next revision. You then incrementally move an increasing portion of the traffic — e.g 5%, then 10%, then 20% ... — to the instances of the new revision. I think this process could be effectively supported by simply adding an weight annotation to pods and having the dispatcher transfer that weight to the corresponding nginx upstream server. It must be possible to change the weight annotation of a pod after it is created and have nginx pick up the change, but no further complexity is required.

Here is how I think this might be used:

- Assume there are 10 instances of the existing revision, each with weight=10
- A client application starts 1 instance for a new revision and gives it a weight of 1. At this point, one in every 101 messages will go to the new revision. The user can increase the weight of the new instance to 10, at which point one in every 11 messages is going to the new revision.
- The user can bring up a second instance with weight 10. At this point one in 6 messages is going to the new revision.

The downside of this very simple design is that the percentage of traffic going to the new revision depends not only on the relative weights of the old and new revision instances, but on their number. You can easily imagine a more complex scheme where dispatcher tracks which instance goes with which revision and provides a way of controlling percentages that does not depend on knowledge of the number of instances. I do not think this extra complexity is needed.

**Comment by AdamMagaluk** [comment]
Implemented in #25
