### ISSUE TITLE
Nginx config support customizable default location.

### ISSUE THREAD

**Issue by AdamMagaluk** [30x/dispatcher#6]
Currently if request comes in that does not match a valid host it returns 444. This needs to be customizable to a target or status code. Default to 444

**Comment by mpnally** [comment]
Jeremy and I had a conversation about what it means to match a valid host. In the previous implementation, we would return a 444 if there was no deployed path for a hostname, even if that hostname was declared by the namespace. I don't think this is ideal. If a hostname is declared at the namespace level, but there are no deployments of paths, I think the error should be 404. Only if the request hostname does not match any namespace-declared hostnames should I get a 444.

**Comment by AdamMagaluk** [comment]
@mpnally Sorry the description does not match the title of the issue that's probably why it was confusing. Just notice i didn't update that.

It should say:

Currently if request comes in that does not match a valid location it returns 404. This needs to be customizable to a target or status code. Default to 404
