### ISSUE TITLE
Get rid of separate label for matching pods and namespaces and use hosts/paths only

### ISSUE THREAD

**Issue by AdamMagaluk** [30x/dispatcher#8]

**Comment by whitlockjc** [comment]
Can you elaborate a little?

**Comment by AdamMagaluk** [comment]
Just making some check lists for stuff that's currently code vs what's in the design doc.

In the k8s-router we used a label to say the pod was routable `routable=true` now we are just using the `edge/paths` and for namespaces `edge/hosts` as labels to select the pods/namespaces.

I had dispatcher originally coded like k8s-router so i got to remove those separate labels and move hosts/paths to labels instead of annotations.

**Comment by whitlockjc** [comment]
That makes sense, thanks.

**Comment by AdamMagaluk** [comment]
@whitlockjc After changing dispatcher I realized we may need to go back to the old approach of having a single label selector to say the pod or namespace is routable and then store all the other configurations in annotations.

We can't store JSON or yaml in a label because it only allows regex `(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')`

**Comment by whitlockjc** [comment]
You're right, the equality check won't help because the `edge/paths` will be an annotation.  What we can do is use the labels being set by enrober instead.  Let's get @jbowen93 to chime in with these labels and we'll update the design document/implementation accordingly.

**Comment by AdamMagaluk** [comment]
Just to clarify:

Namespaces have:
- `edge/hosts` -> JSON/maybe YAML
- `edge/org` -> String
- `edge/env` -> String

Pods have:
- `edge/paths` -> JSON/maybe YAML
- `edge/app.name` -> ?
- `edge/app.rev` -> ?

Should all the above be annotations and we include two new labels for `edge/routable:true` and `edge/namespace:true` that we select on.

**Comment by whitlockjc** [comment]
I'm not against having a new label but I would say that by having the final two _(`edge/app.name` and `edge/app.rev`)_ present _should_ be enough for now.  Thoughts?

**Comment by AdamMagaluk** [comment]
We could do it that way, no new labels. `edge/org` and `edge/env` are labels for namespaces and we can select if present for them since they're strings they work. Same for pods but with `edge/app.name` and `edge/app.rev`. Enrober will have to ensure app name and revision have the same constraints as a k8s label value.

`edge/paths` and `edge/hosts` will have to stay as annotations.

**Comment by AdamMagaluk** [comment]
Actually i'm having second thoughts on that approach, one reason i liked the `edge/routable:true` and `edge/namespace:true` originally was that it allowed us to take namespaces/pods out of rotation without deleting or removing data from resource. Just mark the label as false and it's removed from routing but left in tact to debug / inspect. 

All the other data could either be annotations or labels if their value is allowed in a label but dispatcher wouldn't select on it.

Thoughts?

**Comment by whitlockjc** [comment]
I tend to agree.  `edge/routable` it is then.

**Comment by AdamMagaluk** [comment]
Any reason to have any other of the values as labels or just keep them all in annotations so we can extend the values if necessary?

**Comment by whitlockjc** [comment]
Having them in labels allows us to filter so I say all non-config stuff should be in labels.

**Comment by AdamMagaluk** [comment]
👍
